### ISSUE TITLE
On OpenBSD 7.3, Lazarus fails to build

### ISSUE THREAD

**Issue by TCH68k** [ibara/openbsd-ports-wip#6]
After the upgrade from 7.2 to 7.3, Lazarus and all applications built by it became dead. I tried to update the ports
```
cd /tmp
ftp https://cdn.openbsd.org/pub/OpenBSD/$(uname -r)/{ports.tar.gz,SHA256.sig}
signify -Cp /etc/signify/openbsd-$(uname -r | cut -c 1,3)-base.pub -x SHA256.sig ports.tar.gz
cd /usr
tar xvzf /tmp/ports.tar.gz
rm /tmp/ports.tar.gz
```
then install Lazarus from your repo
```
git clone --depth 1 https://github.com/ibara/openbsd-ports-wip /tmp/obsd-wip
cp -r /tmp/obsd-wip/devel/lazarus /usr/ports/devel
rm -r /tmp/obsd-wip
cd /usr/ports/devel/lazarus
pkg_add fpc gmake libiconv gtk+2
pkg_delete lazarus
make install
```
only to get this as a result:
```
Cloning into '/tmp/obsd-wip'...
remote: Enumerating objects: 1551, done.
remote: Counting objects: 100% (1551/1551), done.
remote: Compressing objects: 100% (1417/1417), done.
remote: Total 1551 (delta 60), reused 1390 (delta 50), pack-reused 0
Receiving objects: 100% (1551/1551), 544.53 KiB | 1.72 MiB/s, done.
Resolving deltas: 100% (60/60), done.
quirks-6.121 signed on 2023-04-14T16:48:08Z
lazarus-2.2.2_0: ok
Running tags: ok
Read shared items: ok
===>  Installing lazarus-2.2.0_0 from /usr/ports/packages/amd64/all/
Can't install lazarus-2.2.0_0 because of libraries
|library atk-1.0.21809.4 not found
| /usr/local/lib/libatk-1.0.so.21810.0 (at-spi2-core-2.46.0p2): bad major
Direct dependencies for lazarus-2.2.0_0 resolve to gtk+2-2.24.33p4 desktop-file-utils-0.26 libiconv-1.17 shared-mime-info-2.2 gmake-4.3 gtk-update-icon-cache-3.24.37 fpc-3.2.2
Full dependency tree is gmake-4.3 python-3.10.11 shared-mime-info-2.2 librsvg-2.54.5p2 libxml-2.10.4 dbus-1.14.6v0 glib2-2.74.6 cairo-1.17.8 libffi-3.4.4 zstd-1.5.5 tiff-4.5.0p0 gnome-icon-theme-symbolic-3.12.0p4 hicolor-icon-theme-0.17 bzip2-1.0.8p0 xz-5.4.1 gnome-icon-theme-3.12.0p6 gettext-runtime-0.21.1 sqlite3-3.41.0 png-1.6.39 fribidi-1.0.12 gtk-update-icon-cache-3.24.37 pcre2-10.37p1 harfbuzz-7.1.0 fpc-3.2.2 pango-1.50.14 gtk+2-2.24.33p4 lz4-1.9.4 gdk-pixbuf-2.42.10 lzo2-2.10p2 jpeg-2.1.4v0 libiconv-1.17 at-spi2-core-2.46.0p2 graphite2-1.3.14 desktop-file-utils-0.26
Couldn't install lazarus-2.2.0_0
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2157 '/var/db/pkg/lazarus-2.2.0_0/+CONTENTS': @/usr/bin/env -i PKG_TMPDIR=/var/tm...)
*** Error 2 in /usr/ports/devel/lazarus (/usr/ports/infrastructure/mk/bsd.port.mk:2600 'install': @lock=lazarus-2.2.0_0;  export _LOCKS_HELD...)
```
AFAIK, atk 1.x was not available in 7.2 either; am i wrong?

**Comment by ibara** [comment]
Looks like maybe you didn't upgrade all your packages after moving to 7.3? Try `doas pkg_add -Uu`

**Comment by TCH68k** [comment]
I tried it, but to no avail. BTW, after the update (but before trying to rebuild it), if i try to run Lazarus, it dies with these errors:
```
lazarus-ide:/usr/X11R6/lib/libX11.so.18.0: /usr/X11R6/lib/libX11.so.17.1 : WARNING: symbol(_XkeyTable) size mismatch, relink your program

(lazarus-ide:63149): GLib-GObject-CRITICAL **: 14:41:12.224: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $00000DC9C1C63E48
  $00000DC9C1C655B2
  $00000DC9C1C65981
  $00000DCA14E8FEDA
  $00000DC9C1C50373
  $00000DCA14E8E372
  $00000DCA14DC4E8E
  $00000DC9C1C4A375
  $00000DC9C1C648EE
  $00000DC9C1C655B2
  $00000DC9C1C65981
  $00000DCA14E8FEDA
  $00000DC9C1C50373
  $00000DCA14E8E372
  $00000DC793E5FF52
  $00000DC793E60077
  $00000DC793CF79F1
[FORMS.PP] ExceptionOccurred 
```
Also, i don't know if it does matter, but until now, out of 3 updgrade attempt, OpenBSD froze 2 times when it installed the sets and printed `"Making all device nodes... done."`, i had to tell VBox7 to reset the VM. The third time it even froze before installing the sets; i had to reboot and `sysupgrade` again, but then it worked.

But in all cases, regardless i ran `pkg_add -u` or `pkg_add -Uu`, Lazarus dies and cannot be rebuilt.

**Comment by TCH68k** [comment]
I asked some help about the system upgrade problems: https://daemonforums.org/showthread.php?t=12396
When i will be able to upgrade my system without problems, it will turn out if the problem was caused by upgrade errors or not.

**Comment by TCH68k** [comment]
Okay, it turned out that the problem was that the ports dir needed to be cleaned, so the solution was `cd /usr/ports/devel/lazarus && make clean='all depends'` after the upgrade and before the rebuild.

What i still do not understand that why did all the Lazarus built programs (including Lazarus IDE) died after the system upgrade? ABI breakage?

**Comment by TCH68k** [comment]
Answer was given: https://daemonforums.org/showthread.php?t=12396#post74131
Yes, there was an ABI breakage between 7.2 and 7.3.

Okay, i think you can close this ticket, as none of the occurred problems were actually connected to your port.
Sorry for wasting your time; was not intentional.
